// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SideWaffle.Creator
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidPackageString = "c1808f49-1e60-4c50-80e5-d4326d20c101";
        public const string guidPackageCmdSetString = "5dc6b5ab-4b09-42fb-bd7f-5b6f6d6b3633";
        public static Guid guidPackage = new Guid(guidPackageString);
        public static Guid guidPackageCmdSet = new Guid(guidPackageCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MenuGroup = 0x0002;
        public const int Menu = 0x0100;
        public const int AddTemplate = 0x1000;
        public const int AddVsHost = 0x1100;
        public const int AddCliHost = 0x1200;
    }
}
