// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SideWaffle.Creator
{
    static class Vsix
    {
        public const string Id = "4c3c294d-9fa1-4745-b761-8eb175792a84";
        public const string Name = "Template Creator";
        public const string Description = @"Makes it easy to create custom project templates.";
        public const string Language = "en-US";
        public const string Version = "0.5";
        public const string Author = "Sayed Ibrahim Hashimi";
        public const string Tags = "template, dotnet";
    }
}
