// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SideWaffle.Creator
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidPackageString = "68e3cc79-56a7-4cc0-b2ef-80a6a54b14991";
        public const string guidPackageCmdSetString = "b6154a9b-021d-4e60-9a60-4dae7af01d28";
        public static Guid guidPackage = new Guid(guidPackageString);
        public static Guid guidPackageCmdSet = new Guid(guidPackageCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MenuGroup = 0x0002;
        public const int Menu = 0x0100;
        public const int AddTemplate = 0x1000;
        public const int AddVsHost = 0x1100;
        public const int AddCliHost = 0x1200;
    }
}
